/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsNewRouteImport } from './routes/groups/new'
import { Route as GroupsGroupIdRouteImport } from './routes/groups/$groupId'
import { Route as GroupsGroupIdExpensesExpenseIdRouteImport } from './routes/groups/$groupId/expenses/$expenseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdExpensesExpenseIdRoute =
  GroupsGroupIdExpensesExpenseIdRouteImport.update({
    id: '/expenses/$expenseId',
    path: '/expenses/$expenseId',
    getParentRoute: () => GroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/new': typeof GroupsNewRoute
  '/groups/$groupId/expenses/$expenseId': typeof GroupsGroupIdExpensesExpenseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/new': typeof GroupsNewRoute
  '/groups/$groupId/expenses/$expenseId': typeof GroupsGroupIdExpensesExpenseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/new': typeof GroupsNewRoute
  '/groups/$groupId/expenses/$expenseId': typeof GroupsGroupIdExpensesExpenseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups/$groupId'
    | '/groups/new'
    | '/groups/$groupId/expenses/$expenseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups/$groupId'
    | '/groups/new'
    | '/groups/$groupId/expenses/$expenseId'
  id:
    | '__root__'
    | '/'
    | '/groups/$groupId'
    | '/groups/new'
    | '/groups/$groupId/expenses/$expenseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRouteWithChildren
  GroupsNewRoute: typeof GroupsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/expenses/$expenseId': {
      id: '/groups/$groupId/expenses/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/groups/$groupId/expenses/$expenseId'
      preLoaderRoute: typeof GroupsGroupIdExpensesExpenseIdRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
  }
}

interface GroupsGroupIdRouteChildren {
  GroupsGroupIdExpensesExpenseIdRoute: typeof GroupsGroupIdExpensesExpenseIdRoute
}

const GroupsGroupIdRouteChildren: GroupsGroupIdRouteChildren = {
  GroupsGroupIdExpensesExpenseIdRoute: GroupsGroupIdExpensesExpenseIdRoute,
}

const GroupsGroupIdRouteWithChildren = GroupsGroupIdRoute._addFileChildren(
  GroupsGroupIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsGroupIdRoute: GroupsGroupIdRouteWithChildren,
  GroupsNewRoute: GroupsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
